name: Build DMG for macOS

on:
  push:
    branches:
      - main  # Hoặc 'master' nếu bạn dùng tên nhánh này
  pull_request:

jobs:
  build:
    runs-on: macos-latest  # Sử dụng môi trường macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Tải code từ repo về máy ảo

    - name: Set up Python
      uses: actions/setup-python@v2  # Thiết lập môi trường Python
      with:
        python-version: '3.x'  # Bạn có thể chỉ định phiên bản Python phù hợp

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app Pillow  # Cài đặt py2app và Pillow (PIL)

    - name: Build DMG
      run: |
        python setup.py py2app  # Đóng gói ứng dụng thành file .app
        hdiutil create -volname MyApp -srcfolder dist/ -ov -format UDZO MyApp.dmg
        # Tạo file .dmg từ file .app

    - name: Upload artifact
      uses: actions/upload-artifact@v2  # Upload file .dmg dưới dạng artifact
      with:
        name: MyApp-dmg
        path: MyApp.dmg
